AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
#Python 2.7 not nodejs 
Resources:
  Parser:
    Type: 'AWS::Serverless::Function'
    Properties:
      # replace with your path for the s3 table for python users have to do dynamodb:Create table
      CodeUri: s3://human-trafficking
      Handler: index.handler
      Runtime: python2.7
      Timeout: 120
      MemorySize: 512
      Policies:
      # Give just CRUD permissions to one table
      - DynamoDBCrudPolicy:
          TableName: !Ref humantrafficking
      Environment:
        Variables:
          DDB_TABLE: !Ref humantrafficking
          CRAWLER_DAYS: 7

  humantrafficking:
    Type: 'AWS::Serverless::SimpleTable'
