AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  
    Type: String
    Default: 'humantrafficking'
    Description: (Required) The name of the new DynamoDB table called humantrafficking
    MinLength: 3
    MaxLength: 50
    AllowedPattern: ^[A-Za-z]+$
    ConstraintDescription: 'Required parameter. Must be characters only. No numbers allowed.'
Resources:
  S3FileStorage:
    Type: AWS::S3::Bucket
  LambdaSave:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      Environment:
        Variables:
          TABLE_NAME: !Ref 
          PRIMARY_KEY: !Sub ${}Id
      Policies:
        - DynamoDBCrudPolicy:
            : !Ref 
      Events:
        S3BucketEvent:
          Type: S3
          Properties:
            Bucket: !Ref S3FileStorage
            Events: s3:ObjectCreated:*
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      : !Ref 
      AttributeDefinitions:
        -
          AttributeName: !Sub "${}Id"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: !Sub "${}Id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
Outputs:
  S3Bucket:
    Value: !Ref S3FileStorage
    Description: The S3 Bucket where the files are stored
  DynamoDBTableArn:
    Value: !GetAtt DynamoDBTable.Arn
    Description: The ARN of your DynamoDB Table
  DynamoDBTableStreamArn:
    Value: !GetAtt DynamoDBTable.StreamArn
    Description: The ARN of your DynamoDB Table Stream